#ifndef LEXERDEF_FILE
#define LEXERDEF_FILE
#include<stdio.h>
#include <stdbool.h>

extern char* symbol_map[];

typedef enum type{PROGRAM, MODULEDECLARATIONS,OTHERMODULES,DRIVERMODULE,
    MODULEDECLARATION,MODULEDEF,MODULE,INPUT_PLIST,N1,RET,OUTPUT_PLIST,
    N2,DATATYPE,TYPE,RANGE,STATEMENTS,STATEMENT,IOSTMT,SIMPLESTMT,DECLARSTMT,
    CONDITIONALSTMT,ITERATIVESTMT,VAR,WHICHID,ASSIGNMENTSTMT,MODULEREUSESTMT,
    WHICHSTMT,LVALUEIDSTMT,LVALUEARRSTMT,EXPRESSION,INDEX,OPTIONAL,IDLIST,N3,
    ARITHMETICEXPR,OP1,TERM,OP2,FACTOR,N4,ARITHMETICORBOOLEANEXPR,ANYTERM,
    LOGICALOP,RELATIONALOP,CASESTMTS,DEFAULT,N7,N8,N9,VALUE,                            //Non-Terminals
    $,
    INTEGER,REAL,BOOLEAN,OF,ARRAY,START,END,DECLARE,DRIVER,GET_VALUE,PRINT,
    USE,WITH,PARAMETERS,TAKES,INPUT,RETURNS,AND,OR,FOR,IN,SWITCH,CASE,BREAK,
    WHILE,PLUS,MINUS,MUL,DIV,LT,LE,GE,GT,EQ,NE,DEF,ENDDEF,DRIVERDEF,DRIVERENDDEF,
    COLON,RANGEOP,SEMICOL,COMMA,ASSIGNOP,SQBO,SQBC,BO,BC,COMMENTMARK,ID,NUM,RNUM,
    EPS,FALSE1,TRUE1} type;                                                                          //Terminals


typedef struct token{
    char* str;
    type tag;
    int line_no;
} token;
#endif
